### ISSUE TITLE
Request for Firmware for ardrone3-milos_pc.ext2.zip for bebop2_multi_uav Project

### ISSUE THREAD

**Issue by Dk-0** [BartlomiejKulecki/bebop2_multi_uav#2]
This link (http://plf.parrot.com/sphinx/firmwares/ardrone3/milos_pc/4.4.2/images/ardrone3-milos_pc.ext2.zip) is no longer valid to download version 4.4.2 of ardrone3- milos_pc.ext2.zip firmware, could you please share this firmware with me, many thanks!

**Comment by BartlomiejKulecki** [comment]
Hello, I uploaded the file on google drive: [link](https://drive.google.com/file/d/1fXRGIUoYaZnumstbjwI7YAwtl1u5j8nT/view?usp=sharing).
However, I don't know if the simulation will work properly because the repository is no longer maintained. 
Good luck!
